### ISSUE TITLE
Allow config to provide specific version of all compilers and centralize config

### ISSUE THREAD

**Issue by dbashford** [dbashford/mimosa#255]
# Breaking Change
- Anyone using `template.handlebars.lib` will have changes to make after this goes in.
- Anyone using `template.emblem.lib` will have changes to make after this goes in.
# ToDo
- [x] Add `compilers.libs` config to validation/documentation
- [x] Update compilers to use `compilers.lib[compilerName]`
- [x] Remove `template.emblem.lib` config
- [x] Remove `template.handlebars.lib` config
# Details

Currently, because of Ember's library version pickiness, only Handlebars and Emblem have config opened up for providing specific versions of compilers.

Lets open that up across the board and allow a user to provide a version for any library.

Might change, but for starters

Defaults:

``` coffeescript
compilers:
  extensionOverrides:{}  # exists already
  libs: null  # new 
```

When used:

``` coffeescript
compilers:
  libs:
    emblem: require('emblem')
    handlebars: require('handlebars')
   ... and so on
```
